name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /pagio

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project & export static files
        run: npm run build
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Commit out folder
        run: |
          git config --global user.email "info@netronaut.de"
          git config --global user.name "gh-pages action"
          git add -f out && git commit -m"Update out folder" && git push
