name: Deploy to GitHub Pages

on:
  push:
    branches: [docs]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BASE_PATH: /pagio
      NEXT_PUBLIC_ASSET_PREFIX: https://netronaut.github.io/pagio/

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Build project & export static files
        run: npm run build
      - name: Configure CNAME and .nojekyll
        run: |
          touch out/.nojekyll
          echo "www.pagetreejs.org" > out/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
