name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main
    - "*-rc"
  pull_request:
    branches:
    - main
    - "*-rc"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    name: Build, lint and test on node and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
        
    - name: npm install, build, lint and test
      run: |
        npm ci
        npm run build
        npm run lint
        npm test
